### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '.\\out\\AndroidManifest.xml'

### ISSUE THREAD

**Issue by horizon365** [yeling/ApkShield#1]
[root@localhost ApkShield-master]# python Shield.py M007008.apk 
Begin decypt
Begin Shield
M007008.apk
java -jar apktool.jar d -f -o out M007008.apk
I: Using Apktool 2.0.0-RC4 on M007008.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values _/_ XMLs...
I: Baksmaling classes.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
Traceback (most recent call last):
  File "Shield.py", line 75, in <module>
    parseXml()
  File "Shield.py", line 32, in parseXml
    tree = xml.dom.minidom.parse(path)
  File "/usr/lib64/python2.7/xml/dom/minidom.py", line 1921, in parse
    return expatbuilder.parse(file)
  File "/usr/lib64/python2.7/xml/dom/expatbuilder.py", line 922, in parse
    fp = open(file, 'rb')
IOError: [Errno 2] No such file or directory: '.\out\AndroidManifest.xml'

是只能用在Windows下吗？可是Windows下报同样的错误。
C:\Python27>python.exe G:\file\ApkShield-master\Shield.py G:\file\ApkShield-master\M007008.apk

**Comment by yeling** [comment]
这个应该是python脚本的问题，可以看下对应的文件，在不在
